// Code generated by protoc-gen-go. DO NOT EDIT.
// source: mygrpc.proto

/*
Package mygrpc is a generated protocol buffer package.

It is generated from these files:
	mygrpc.proto

It has these top-level messages:
	Service
	ServiceChain
	ServiceChains
	ServiceDescriptor
	ServiceChainDescriptor
	ServiceChainDescriptors
*/
package mygrpc

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Service struct {
	// name of the service
	SvcName string `protobuf:"bytes,1,opt,name=svc_name,json=svcName" json:"svc_name,omitempty"`
	// position of the service in the service chain
	SvcPos int32 `protobuf:"varint,2,opt,name=svc_pos,json=svcPos" json:"svc_pos,omitempty"`
}

func (m *Service) Reset()                    { *m = Service{} }
func (m *Service) String() string            { return proto.CompactTextString(m) }
func (*Service) ProtoMessage()               {}
func (*Service) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Service) GetSvcName() string {
	if m != nil {
		return m.SvcName
	}
	return ""
}

func (m *Service) GetSvcPos() int32 {
	if m != nil {
		return m.SvcPos
	}
	return 0
}

type ServiceChain struct {
	// unique identifier of the service chain
	ChainId int32 `protobuf:"varint,1,opt,name=chain_id,json=chainId" json:"chain_id,omitempty"`
	// length of the service chain
	ChainLen int32 `protobuf:"varint,2,opt,name=chain_len,json=chainLen" json:"chain_len,omitempty"`
	// services froming the service chain
	Chain []*Service `protobuf:"bytes,3,rep,name=chain" json:"chain,omitempty"`
}

func (m *ServiceChain) Reset()                    { *m = ServiceChain{} }
func (m *ServiceChain) String() string            { return proto.CompactTextString(m) }
func (*ServiceChain) ProtoMessage()               {}
func (*ServiceChain) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ServiceChain) GetChainId() int32 {
	if m != nil {
		return m.ChainId
	}
	return 0
}

func (m *ServiceChain) GetChainLen() int32 {
	if m != nil {
		return m.ChainLen
	}
	return 0
}

func (m *ServiceChain) GetChain() []*Service {
	if m != nil {
		return m.Chain
	}
	return nil
}

type ServiceChains struct {
	Chains []*ServiceChain `protobuf:"bytes,1,rep,name=chains" json:"chains,omitempty"`
}

func (m *ServiceChains) Reset()                    { *m = ServiceChains{} }
func (m *ServiceChains) String() string            { return proto.CompactTextString(m) }
func (*ServiceChains) ProtoMessage()               {}
func (*ServiceChains) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *ServiceChains) GetChains() []*ServiceChain {
	if m != nil {
		return m.Chains
	}
	return nil
}

type ServiceDescriptor struct {
	// name of the service
	SvcName string `protobuf:"bytes,1,opt,name=svc_name,json=svcName" json:"svc_name,omitempty"`
	// description of the service
	SvcDesc string `protobuf:"bytes,2,opt,name=svc_desc,json=svcDesc" json:"svc_desc,omitempty"`
	// position of the service in the service chain
	SvcPos int32 `protobuf:"varint,3,opt,name=svc_pos,json=svcPos" json:"svc_pos,omitempty"`
}

func (m *ServiceDescriptor) Reset()                    { *m = ServiceDescriptor{} }
func (m *ServiceDescriptor) String() string            { return proto.CompactTextString(m) }
func (*ServiceDescriptor) ProtoMessage()               {}
func (*ServiceDescriptor) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *ServiceDescriptor) GetSvcName() string {
	if m != nil {
		return m.SvcName
	}
	return ""
}

func (m *ServiceDescriptor) GetSvcDesc() string {
	if m != nil {
		return m.SvcDesc
	}
	return ""
}

func (m *ServiceDescriptor) GetSvcPos() int32 {
	if m != nil {
		return m.SvcPos
	}
	return 0
}

type ServiceChainDescriptor struct {
	// unique identifier of the service chain
	ChainId int32 `protobuf:"varint,1,opt,name=chain_id,json=chainId" json:"chain_id,omitempty"`
	// length of the service chain
	ChainLen int32 `protobuf:"varint,2,opt,name=chain_len,json=chainLen" json:"chain_len,omitempty"`
	// descriptions of the services froming the service chain
	ChainDesc []*ServiceDescriptor `protobuf:"bytes,3,rep,name=chain_desc,json=chainDesc" json:"chain_desc,omitempty"`
}

func (m *ServiceChainDescriptor) Reset()                    { *m = ServiceChainDescriptor{} }
func (m *ServiceChainDescriptor) String() string            { return proto.CompactTextString(m) }
func (*ServiceChainDescriptor) ProtoMessage()               {}
func (*ServiceChainDescriptor) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *ServiceChainDescriptor) GetChainId() int32 {
	if m != nil {
		return m.ChainId
	}
	return 0
}

func (m *ServiceChainDescriptor) GetChainLen() int32 {
	if m != nil {
		return m.ChainLen
	}
	return 0
}

func (m *ServiceChainDescriptor) GetChainDesc() []*ServiceDescriptor {
	if m != nil {
		return m.ChainDesc
	}
	return nil
}

type ServiceChainDescriptors struct {
	ChainDescs []*ServiceDescriptor `protobuf:"bytes,1,rep,name=chain_descs,json=chainDescs" json:"chain_descs,omitempty"`
}

func (m *ServiceChainDescriptors) Reset()                    { *m = ServiceChainDescriptors{} }
func (m *ServiceChainDescriptors) String() string            { return proto.CompactTextString(m) }
func (*ServiceChainDescriptors) ProtoMessage()               {}
func (*ServiceChainDescriptors) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *ServiceChainDescriptors) GetChainDescs() []*ServiceDescriptor {
	if m != nil {
		return m.ChainDescs
	}
	return nil
}

func init() {
	proto.RegisterType((*Service)(nil), "mygrpc.Service")
	proto.RegisterType((*ServiceChain)(nil), "mygrpc.ServiceChain")
	proto.RegisterType((*ServiceChains)(nil), "mygrpc.ServiceChains")
	proto.RegisterType((*ServiceDescriptor)(nil), "mygrpc.ServiceDescriptor")
	proto.RegisterType((*ServiceChainDescriptor)(nil), "mygrpc.ServiceChainDescriptor")
	proto.RegisterType((*ServiceChainDescriptors)(nil), "mygrpc.ServiceChainDescriptors")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for MyGrpc service

type MyGrpcClient interface {
	// Get a service chain descriptor according to a request indicating to a single chain
	GetChainReqResp(ctx context.Context, in *ServiceChain, opts ...grpc.CallOption) (*ServiceChainDescriptor, error)
	// Get service chain descriptors according to a request indicating to multiple chains
	GetChainsReqResps(ctx context.Context, in *ServiceChains, opts ...grpc.CallOption) (MyGrpc_GetChainsReqRespsClient, error)
	// Get a descriptor describing multiple service chains according to requests of which indicating to a single chain each
	GetChainsReqsResp(ctx context.Context, opts ...grpc.CallOption) (MyGrpc_GetChainsReqsRespClient, error)
	// Get multiple service chain descriptors according to requests of which indicating to a single chain each
	GetChainReqsResps(ctx context.Context, opts ...grpc.CallOption) (MyGrpc_GetChainReqsRespsClient, error)
}

type myGrpcClient struct {
	cc *grpc.ClientConn
}

func NewMyGrpcClient(cc *grpc.ClientConn) MyGrpcClient {
	return &myGrpcClient{cc}
}

func (c *myGrpcClient) GetChainReqResp(ctx context.Context, in *ServiceChain, opts ...grpc.CallOption) (*ServiceChainDescriptor, error) {
	out := new(ServiceChainDescriptor)
	err := grpc.Invoke(ctx, "/mygrpc.MyGrpc/GetChainReqResp", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *myGrpcClient) GetChainsReqResps(ctx context.Context, in *ServiceChains, opts ...grpc.CallOption) (MyGrpc_GetChainsReqRespsClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_MyGrpc_serviceDesc.Streams[0], c.cc, "/mygrpc.MyGrpc/GetChainsReqResps", opts...)
	if err != nil {
		return nil, err
	}
	x := &myGrpcGetChainsReqRespsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type MyGrpc_GetChainsReqRespsClient interface {
	Recv() (*ServiceChainDescriptor, error)
	grpc.ClientStream
}

type myGrpcGetChainsReqRespsClient struct {
	grpc.ClientStream
}

func (x *myGrpcGetChainsReqRespsClient) Recv() (*ServiceChainDescriptor, error) {
	m := new(ServiceChainDescriptor)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *myGrpcClient) GetChainsReqsResp(ctx context.Context, opts ...grpc.CallOption) (MyGrpc_GetChainsReqsRespClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_MyGrpc_serviceDesc.Streams[1], c.cc, "/mygrpc.MyGrpc/GetChainsReqsResp", opts...)
	if err != nil {
		return nil, err
	}
	x := &myGrpcGetChainsReqsRespClient{stream}
	return x, nil
}

type MyGrpc_GetChainsReqsRespClient interface {
	Send(*ServiceChain) error
	CloseAndRecv() (*ServiceChainDescriptors, error)
	grpc.ClientStream
}

type myGrpcGetChainsReqsRespClient struct {
	grpc.ClientStream
}

func (x *myGrpcGetChainsReqsRespClient) Send(m *ServiceChain) error {
	return x.ClientStream.SendMsg(m)
}

func (x *myGrpcGetChainsReqsRespClient) CloseAndRecv() (*ServiceChainDescriptors, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(ServiceChainDescriptors)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *myGrpcClient) GetChainReqsResps(ctx context.Context, opts ...grpc.CallOption) (MyGrpc_GetChainReqsRespsClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_MyGrpc_serviceDesc.Streams[2], c.cc, "/mygrpc.MyGrpc/GetChainReqsResps", opts...)
	if err != nil {
		return nil, err
	}
	x := &myGrpcGetChainReqsRespsClient{stream}
	return x, nil
}

type MyGrpc_GetChainReqsRespsClient interface {
	Send(*ServiceChain) error
	Recv() (*ServiceChainDescriptor, error)
	grpc.ClientStream
}

type myGrpcGetChainReqsRespsClient struct {
	grpc.ClientStream
}

func (x *myGrpcGetChainReqsRespsClient) Send(m *ServiceChain) error {
	return x.ClientStream.SendMsg(m)
}

func (x *myGrpcGetChainReqsRespsClient) Recv() (*ServiceChainDescriptor, error) {
	m := new(ServiceChainDescriptor)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for MyGrpc service

type MyGrpcServer interface {
	// Get a service chain descriptor according to a request indicating to a single chain
	GetChainReqResp(context.Context, *ServiceChain) (*ServiceChainDescriptor, error)
	// Get service chain descriptors according to a request indicating to multiple chains
	GetChainsReqResps(*ServiceChains, MyGrpc_GetChainsReqRespsServer) error
	// Get a descriptor describing multiple service chains according to requests of which indicating to a single chain each
	GetChainsReqsResp(MyGrpc_GetChainsReqsRespServer) error
	// Get multiple service chain descriptors according to requests of which indicating to a single chain each
	GetChainReqsResps(MyGrpc_GetChainReqsRespsServer) error
}

func RegisterMyGrpcServer(s *grpc.Server, srv MyGrpcServer) {
	s.RegisterService(&_MyGrpc_serviceDesc, srv)
}

func _MyGrpc_GetChainReqResp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServiceChain)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MyGrpcServer).GetChainReqResp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mygrpc.MyGrpc/GetChainReqResp",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MyGrpcServer).GetChainReqResp(ctx, req.(*ServiceChain))
	}
	return interceptor(ctx, in, info, handler)
}

func _MyGrpc_GetChainsReqResps_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ServiceChains)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MyGrpcServer).GetChainsReqResps(m, &myGrpcGetChainsReqRespsServer{stream})
}

type MyGrpc_GetChainsReqRespsServer interface {
	Send(*ServiceChainDescriptor) error
	grpc.ServerStream
}

type myGrpcGetChainsReqRespsServer struct {
	grpc.ServerStream
}

func (x *myGrpcGetChainsReqRespsServer) Send(m *ServiceChainDescriptor) error {
	return x.ServerStream.SendMsg(m)
}

func _MyGrpc_GetChainsReqsResp_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(MyGrpcServer).GetChainsReqsResp(&myGrpcGetChainsReqsRespServer{stream})
}

type MyGrpc_GetChainsReqsRespServer interface {
	SendAndClose(*ServiceChainDescriptors) error
	Recv() (*ServiceChain, error)
	grpc.ServerStream
}

type myGrpcGetChainsReqsRespServer struct {
	grpc.ServerStream
}

func (x *myGrpcGetChainsReqsRespServer) SendAndClose(m *ServiceChainDescriptors) error {
	return x.ServerStream.SendMsg(m)
}

func (x *myGrpcGetChainsReqsRespServer) Recv() (*ServiceChain, error) {
	m := new(ServiceChain)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _MyGrpc_GetChainReqsResps_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(MyGrpcServer).GetChainReqsResps(&myGrpcGetChainReqsRespsServer{stream})
}

type MyGrpc_GetChainReqsRespsServer interface {
	Send(*ServiceChainDescriptor) error
	Recv() (*ServiceChain, error)
	grpc.ServerStream
}

type myGrpcGetChainReqsRespsServer struct {
	grpc.ServerStream
}

func (x *myGrpcGetChainReqsRespsServer) Send(m *ServiceChainDescriptor) error {
	return x.ServerStream.SendMsg(m)
}

func (x *myGrpcGetChainReqsRespsServer) Recv() (*ServiceChain, error) {
	m := new(ServiceChain)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _MyGrpc_serviceDesc = grpc.ServiceDesc{
	ServiceName: "mygrpc.MyGrpc",
	HandlerType: (*MyGrpcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetChainReqResp",
			Handler:    _MyGrpc_GetChainReqResp_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetChainsReqResps",
			Handler:       _MyGrpc_GetChainsReqResps_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetChainsReqsResp",
			Handler:       _MyGrpc_GetChainsReqsResp_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "GetChainReqsResps",
			Handler:       _MyGrpc_GetChainReqsResps_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "mygrpc.proto",
}

func init() { proto.RegisterFile("mygrpc.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 361 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x93, 0x6f, 0x4b, 0x3a, 0x41,
	0x10, 0xc7, 0x5d, 0xc5, 0xf3, 0xe7, 0xe8, 0x0f, 0x71, 0xa9, 0x3c, 0x0b, 0x4a, 0x16, 0x82, 0x7b,
	0x10, 0x22, 0xf6, 0x24, 0x02, 0x1f, 0x15, 0x88, 0x50, 0x16, 0x1b, 0x3d, 0x16, 0x5d, 0x97, 0x3a,
	0xe8, 0xfe, 0xb4, 0x23, 0x07, 0xbe, 0x85, 0x5e, 0x57, 0x2f, 0x2c, 0x6e, 0x77, 0xed, 0x54, 0x8e,
	0x0b, 0x7c, 0x36, 0x3b, 0xdf, 0x99, 0xcf, 0xcc, 0x7c, 0x8f, 0x83, 0x66, 0xb0, 0x7e, 0x53, 0xb1,
	0xe8, 0xc7, 0x2a, 0x5a, 0x45, 0xd4, 0x31, 0x2f, 0x36, 0x82, 0xda, 0x8b, 0x54, 0x89, 0x2f, 0x24,
	0xed, 0xc2, 0x3f, 0x4c, 0xc4, 0x2c, 0x9c, 0x07, 0xd2, 0x25, 0x3d, 0xe2, 0xd5, 0x79, 0x0d, 0x13,
	0x31, 0x9d, 0x07, 0x92, 0x76, 0x20, 0x0d, 0x67, 0x71, 0x84, 0x6e, 0xb9, 0x47, 0xbc, 0x2a, 0x77,
	0x30, 0x11, 0xcf, 0x11, 0xb2, 0x00, 0x9a, 0xb6, 0xfd, 0xee, 0x7d, 0xee, 0x87, 0x29, 0x43, 0xa4,
	0xc1, 0xcc, 0x5f, 0x6a, 0x46, 0x95, 0xd7, 0xf4, 0x7b, 0xb2, 0xa4, 0x67, 0x50, 0x37, 0xd2, 0x87,
	0x0c, 0x2d, 0xc5, 0xd4, 0x3e, 0xc8, 0x90, 0x5e, 0x42, 0x55, 0xc7, 0x6e, 0xa5, 0x57, 0xf1, 0x1a,
	0xc3, 0x56, 0xdf, 0x2e, 0x6b, 0xe1, 0xdc, 0xa8, 0x6c, 0x04, 0xff, 0xb7, 0xc7, 0x21, 0xbd, 0x02,
	0x47, 0x2b, 0xe8, 0x12, 0xdd, 0x78, 0xb4, 0xd7, 0xa8, 0xcb, 0xb8, 0xad, 0x61, 0x0b, 0x68, 0xdb,
	0xfc, 0xbd, 0x44, 0xa1, 0xfc, 0x78, 0x15, 0xa9, 0xa2, 0xb3, 0xad, 0xb4, 0x94, 0x28, 0xf4, 0xc6,
	0x46, 0x4a, 0x7b, 0xb7, 0x1d, 0xa9, 0xec, 0x38, 0xf2, 0x45, 0xe0, 0x64, 0x7b, 0xf8, 0xee, 0xa4,
	0x83, 0xcc, 0xb9, 0x01, 0x30, 0xa2, 0x5e, 0xc4, 0x38, 0xd4, 0xdd, 0x3b, 0x34, 0x1b, 0xc3, 0x0d,
	0x29, 0x4d, 0xb0, 0x57, 0xe8, 0xe4, 0xef, 0x82, 0xf4, 0x16, 0x1a, 0x19, 0x74, 0x63, 0x5f, 0x01,
	0x15, 0x7e, 0xa9, 0x38, 0xfc, 0x2e, 0x83, 0xf3, 0xb8, 0x1e, 0xab, 0x58, 0xd0, 0x09, 0xb4, 0xc6,
	0x72, 0x65, 0x6c, 0x96, 0x9f, 0x5c, 0x62, 0x4c, 0x73, 0xbf, 0xc1, 0xe9, 0x79, 0x5e, 0x36, 0xe3,
	0xb3, 0x12, 0x9d, 0x42, 0x7b, 0x83, 0x42, 0xcb, 0x42, 0x7a, 0x9c, 0xd7, 0x86, 0x7f, 0xd3, 0x06,
	0x64, 0x9f, 0x87, 0x05, 0xcb, 0x5d, 0x14, 0xe3, 0x90, 0x95, 0x3c, 0x42, 0x9f, 0x32, 0xde, 0x06,
	0x87, 0x87, 0x1e, 0xeb, 0x91, 0x01, 0x59, 0x38, 0xfa, 0x57, 0xbc, 0xfe, 0x09, 0x00, 0x00, 0xff,
	0xff, 0xed, 0x2d, 0xa0, 0xbb, 0x9a, 0x03, 0x00, 0x00,
}
